### ISSUE TITLE
Nothing here :)

### ISSUE THREAD

**Issue by sapir** [esp-rs/esp32#2]
There's an esp32-sys crate in the esp32 quickstart repo here:
https://github.com/lexxvir/esp32-hello

I made a fork containing just the esp32-sys crate here:
https://github.com/sapir/esp32-sys

I propose to use it, at least as the basis for any further work.

**Comment by MabezDev** [comment]
Hey, sorry for taking so long, I've only just seen this.

I'd like to keep the this repo pure Rust (I hope to start this once object generation etc is in the llvm fork), that said, if you wanted to move your project to this org under esp32-sys or something like that I'd be happy to have it there.

**Comment by jeandudey** [comment]
@MabezDev Could you initialize it?

**Comment by MabezDev** [comment]
Whoops, done :)
